---
- name: Create Aptly service
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  template:
    src: aptly-api.service.j2
    dest: /lib/systemd/system/{{ aptly_api_service_name }}.service
    backup: true
  notify:
    - reload-daemon
    - restart-aptly-api

- name: Create Aptly service
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  service:
    name: "{{ aptly_api_service_name }}.service"
    state: started
    enabled: true

- name: Wait for Aptly service start
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  wait_for:
    port: '{{ aptly_api_port }}'
    # host: localhost
    state: started
