---
- name: Add gpg key Aptly 4 
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  apt_key:
    url: https://www.aptly.info/pubkey.txt
    state: present

- name: Add repo Aptly 4 Debian\Ubuntu
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  apt_repository:
    repo: deb http://repo.aptly.info/ {{ aptly_repo_version_fact }} main
    state: present
    filename: aptly
