---
- name: Install Apache
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  apt:
    name:
      - apache2
    state: present
    install_recommends: true

- name: Disable 000-default.conf
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf

- name: Allow access deb repo over http
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - aptly_www_webdav_access == false
  become: true
  template:
    src: 80-aptly-share.conf.apache.j2
    dest: /etc/apache2/sites-available/080-aptly-share.conf
    mode: '644'
    backup: true

- name: Allow access deb repo over wedav
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - aptly_www_webdav_access == true
  become: true
  template:
    src: 80-aptly-share-webdav.conf.apache.j2
    dest: /etc/apache2/sites-available/080-aptly-share.conf
    mode: '644'
    backup: true

# http://ashep.org/2011/nastrojka-webdav-pod-apache2/
- name: Enable apache modules 4 webdav
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - aptly_www_webdav_access == true
  become: true
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - dav_fs
    - dav

- name: Enable share aptly
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  command: a2ensite 080-aptly-share.conf
  args:
    creates: /etc/apache2/sites-enabled/080-aptly-share.conf
  # notify: restart-apache

- name: Config port
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  lineinfile:
    dest: /etc/apache2/ports.conf
    line: 'Listen {{ aptly_www_port }}'
    insertafter: '^# /etc/apache2/sites-enabled/000-default.conf'
    backup: true
  tags:
    - www-port

- name: Comment default port
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  replace:
    path: /etc/apache2/ports.conf
    regexp: "^Listen 80"
    replace: '# Listen 80'
    backup: true
  tags:
    - www-port

- name: Validate Apache configuration
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  command: apache2ctl configtest
  register: apache_configtest
  changed_when: apache_configtest.rc != 0

- name: Enable and start Apache service
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  service:
    name: apache2
    state: started
    enabled: true
