---
- name: Install Lighttpd
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  apt:
    name:
      - lighttpd
    state: present
    install_recommends: true

- name: Install Lighttpd
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - aptly_www_webdav_access == true
  become: true
  apt:
    name:
      - lighttpd-mod-webdav
    state: present
    install_recommends: true

#--- Classic share ---#

- name: Allow access deb repo over http
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  template:
    src: 80-aptly-share.conf.lighttpd.j2
    dest: /etc/lighttpd/conf-available/80-aptly-share.conf
    mode: '644'
    backup: true

- name: Enable share aptly
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  command: lighttpd-enable-mod aptly-share
  args:
    chdir: /etc/lighttpd/conf-enabled
    creates: 80-aptly-share.conf
  notify: restart-lighttpd

- name: Enable dir listing
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  command: lighttpd-enable-mod dir-listing
  args:
    chdir: /etc/lighttpd/conf-enabled
    creates: 10-dir-listing.conf
  notify: restart-lighttpd

#--- Webdav share ---#

- name: Allow access deb repo over wedav
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - aptly_www_webdav_access == true
  become: true
  template:
    src: 80-aptly-share-webdav.conf.lighttpd.j2
    dest: /etc/lighttpd/conf-available/80-aptly-share-webdav.conf
    mode: '644'
    backup: true

- name: Enable webdav
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - aptly_www_webdav_access == true
  become: true
  command: lighttpd-enable-mod aptly-share-webdav
  args:
    chdir: /etc/lighttpd/conf-enabled
    creates: 80-aptly-share-webdav.conf

- name: Config port
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  replace:
    path: /etc/lighttpd/lighttpd.conf
    regexp: "^server.port.*"
    replace: 'server.port                 = {{ aptly_www_port }}'
    backup: true
  tags:
    - www-port

#--- Service run ---#

- name: Enable and start lighttpd service
  when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
  become: true
  service:
    name: lighttpd
    state: started
    enabled: true
