---
- name: update-apt-repo-cache
  become: true
  apt:
    update_cache: true
    force: true

- name: reload-daemon
  become: true
  command: systemctl daemon-reload

- name: restart-aptly-api
  become: true
  service:
    name: "{{ aptly_api_service_name }}"
    state: restarted

- name: update-mount-points
  become: true
  command: mount -a
  # https://www.ansiblejunky.com/blog/ansible-101-disable-warning-messages/
  args:
    warn: false

- name: restart-apache
  become: true
  service:
    name: apache2
    state: restarted

- name: restart-lighttpd
  become: true
  service:
    name: lighttpd
    state: restarted

- name: restart-nginx
  become: true
  service:
    name: nginx
    state: restarted
